all: analyze basler probe 

GSL_INC = APP3-CPP/gsl-1.15/
APP3_CPP_INC = APP3-CPP
INC = -I${APP3_CPP_INC} -I${GSL_INC}

GSL_LIB = -LAPP3-CPP/gsl-1.15/.libs/ -LAPP3-CPP/gsl-1.15/cblas/.libs/
CCFITS_LIB = APP3-CPP/CCfits/.libs/libCCfits.so
TIFF_LIB = APP3-CPP/tiff-3.9.4/libtiff/.libs/libtiff.so

RUN_TIME_PATHS = -RAPP3-CPP/gsl-1.15/.libs/:APP3-CPP/gsl-1.15/cblas/.libs/:APP3-CPP/CCfits/.libs/:APP3-CPP/tiff-3.9.4/libtiff/.libs/

CFLAGS =  -Wall ${INC}
LFLAGS = ${GSL_LIB} -lgsl -lgslcblas -lm ${CCFITS_LIB} ${TIFF_LIB} -Xlinker ${RUN_TIME_PATHS}

objs = APP3-CPP/funcs/funcs.o APP3-CPP/utils/utils.o APP3-CPP/qini/qini_utils.o APP3-CPP/fits/fits.o 
 
analyze: analyze.o ${objs} Fermions.h
	g++ analyze.o ${objs} ${LFLAGS} -o analyze
	chmod a+w analyze 
	cp -v analyze APP3-CPP/bin/analyze
	

basler: basler.o ${objs} Fermions.h
	g++ basler.o ${objs} ${LFLAGS} -o basler
	chmod a+w basler
	cp -v basler APP3-CPP/bin/basler

probe: probe.o ${objs} Fermions.h
	g++ probe.o ${objs} ${LFLAGS} -o probe
	chmod a+w probe
	cp -v probe APP3-CPP/bin/probe

clean:
	rm -f *.o

.cpp.o: 
	indent $<
	g++ ${CFLAGS} $< -c




