all: testfits

GSL_INC = APP3-CPP/gsl-1.15/
APP3_CPP_INC = APP3-CPP/
INC = -I${APP3_CPP_INC} -I${GSL_INC}

GSL_LIB = -LAPP3-CPP/gsl-1.15/.libs/ -LAPP3-CPP/gsl-1.15/cblas/.libs/
CCFITS_LIB = APP3-CPP/CCfits/.libs/libCCfits.so
TIFF_LIB = APP3-CPP/tiff-3.9.4/libtiff/.libs/libtiff.so

RUN_TIME_PATHS = -RAPP3-CPP/gsl-1.15/.libs/:APP3-CPP/gsl-1.15/cblas/.libs/:APP3-CPP/CCfits/.libs/:APP3-CPP/tiff-3.9.4/libtiff/.libs/

CFLAGS = -Wall ${INC} -fopenmp 
LFLAGS = ${GSL_LIB} -lgsl -lgslcblas -lm ${CCFITS_LIB} ${TIFF_LIB} -Xlinker ${RUN_TIME_PATHS}

objs =   ../qini/qini_utils.o ../utils/utils.o ../funcs/funcs.o 

testfits: testfits.o fits.o
	g++  $^ ${objs} ${LFLAGS} -o testfits

clean:
	rm -f *.o

.cpp.o:
	indent $<
	g++ ${CFLAGS} $< -c




