all: testfuncs

GSL_INC = APP3-CPP/gsl-1.15/
APP3_CPP_INC = APP3-CPP/
INC = -I${APP3_CPP_INC} -I${GSL_INC}

GSL_LIB = -LAPP3-CPP/gsl-1.15/.libs/ -LAPP3-CPP/gsl-1.15/cblas/.libs

RUN_TIME_PATHS = -RAPP3-CPP/gsl-1.15/.libs/:APP3-CPP/gsl-1.15/cblas/.libs/

CFLAGS = -Wall ${INC} 
LFLAGS = ${GSL_LIB} -lgsl -lgslcblas -lm -Xlinker ${RUN_TIME_PATHS} 


objs =  

testfuncs: testfuncs.o funcs.o
	g++  $^ ${objs} ${LFLAGS} -o testfuncs

clean:
	rm -f *.o

.cpp.o:
	indent $<
	g++ ${CFLAGS} $< -c




